### PR TITLE
Add sidebar menu with all Pokemon options

### LINKED ISSUE #4: Create Lateral Menu to Access All Pokémon
**Description:**  
Implement a lateral (side) menu that allows users to scroll through and select any Pokémon from the Pokédex. This menu should be accessible from any screen and should contain all the Pokémon names and small icons for easy navigation.

- Fetch the list of all Pokémon from the JSON file.
- Implement a scrollable lateral menu that shows Pokémon names and small icons.
- Ensure the user can select a Pokémon from this menu and update the main display accordingly.

**Expected Outcome:**  
A side menu should allow users to scroll through all Pokémon and quickly access the one they want to view.

### PR DESCRIPTION
**Pull request by parker-research**
Fixes #4.

Note: This PR also refactors the way the JSON file is read to avoid re-reading it on every load. It uses a `cache` decorator to do so.

### CODE REVIEW

**Comment by MatheusMarinhoLeca** [comment]
Try to resolve the conflicts and provide tests.

**Comment by parker-research** [comment]
Added test case for new file loading function. Fixed conflicts.

**Comment by MatheusMarinhoLeca** [comment]
Please fix your test cases for your PR to be accepted.

**Comment by parker-research** [comment]
What do you mean "fix my test cases"?

**Comment by MatheusMarinhoLeca** [comment]
> What do you mean "fix my test cases"?
To assert there are 1,025 Pokémon in total, not 800, as I mentioned in a private conversation with you.

**Pull request merged**
